spring.application.name=CityGuardian
jwt.secret=secretsecretsecretsecretsecretsecretsecretsecret
spring.data.mongodb.database=city-guardian-db
spring.data.mongodb.uri=mongodb+srv://2021ivancardona:CityGuardian2025$@cluster0.yot39ad.mongodb.net/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cityguardianenvios@gmail.com
spring.mail.password=jrxs klpn stkm czom
cloudinary.cloud-name=dfacja0b6
cloudinary.api-key=872464731894623
cloudinary.api-secret=foT9t7di-qnm7gHPyiuE-GdXHO4
firebase.credentials.path=classpath:firebase-service-account.json
firebase.project.id=cityguardian-b35a8